SIGSEND_TESTS_SOURCES =



SOURCES += $(SIGSEND_TESTS_SOURCES:%.c=signal/sigsend/tests/%.c)
SOURCES += $(wildcard signal/sigsend/tests/*_config.c)
SEC_SOURCES += $(wildcard signal/sigsend/tests/*.sec)

