ENVIRON_TESTS_SOURCES =



SOURCES += $(ENVIRON_TESTS_SOURCES:%.c=process/environ/tests/%.c)
SOURCES += $(wildcard process/environ/tests/*_config.c)
SEC_SOURCES += $(wildcard process/environ/tests/*.sec)

