WCTRANS_SOURCES =



SOURCES += $(WCTRANS_SOURCES:%.c=locale/wctrans/%.c)
SOURCES += $(wildcard locale/wctrans/*_config.c)
SEC_SOURCES += $(wildcard locale/wctrans/*.sec)

include locale/wctrans/tests/Makefile

