WINDOW_SOURCES =



SOURCES += $(WINDOW_SOURCES:%.c=ncurses/window/%.c)
SOURCES += $(wildcard ncurses/window/*_config.c)
SEC_SOURCES += $(wildcard ncurses/window/*.sec)

include ncurses/window/tests/Makefile

