TIME_CONVERSION_TESTS_SOURCES =



SOURCES += $(TIME_CONVERSION_TESTS_SOURCES:%.c=time/conversion/tests/%.c)
SOURCES += $(wildcard time/conversion/tests/*_config.c)
SEC_SOURCES += $(wildcard time/conversion/tests/*.sec)

