TEXTDOMAIN_TESTS_SOURCES =



SOURCES += $(TEXTDOMAIN_TESTS_SOURCES:%.c=locale/textdomain/tests/%.c)
SOURCES += $(wildcard locale/textdomain/tests/*_config.c)
SEC_SOURCES += $(wildcard locale/textdomain/tests/*.sec)

