NCURSES_STRING_SOURCES = add_agent.c input_agent.c insert_agent.c printf_agent.c printf_agent_vwprintw.c scanf_agent.c scanf_agent_vwscanw.c


SOURCES += $(NCURSES_STRING_SOURCES:%.c=ncurses/string/%.c)

