RESOURCES_SOURCES =



SOURCES += $(RESOURCES_SOURCES:%.c=process/resources/%.c)
SOURCES += $(wildcard process/resources/*_config.c)
SEC_SOURCES += $(wildcard process/resources/*.sec)

include process/resources/tests/Makefile

