PTHREAD_TESTS_SOURCES =

SOURCES += $(PTHREAD_TESTS_SOURCES:%.c=pthread/pthread/tests/%.c)

SOURCES += $(wildcard pthread/pthread/tests/*_config.c)
SEC_SOURCES += $(wildcard pthread/pthread/tests/*.sec)

