CTRANS_SOURCES =



SOURCES += $(CTRANS_SOURCES:%.c=locale/ctrans/%.c)
SOURCES += $(wildcard locale/ctrans/*_config.c)
SEC_SOURCES += $(wildcard locale/ctrans/*.sec)

include locale/ctrans/tests/Makefile

