SIGCTRL_TESTS_SOURCES =



SOURCES += $(SIGCTRL_TESTS_SOURCES:%.c=signal/sigctrl/tests/%.c)
SOURCES += $(wildcard signal/sigctrl/tests/*_config.c)
SEC_SOURCES += $(wildcard signal/sigctrl/tests/*.sec)

