COMPRESS_TESTS_SOURCES =



SOURCES += $(COMPRESS_TESTS_SOURCES:%.c=util/compress/tests/%.c)
SOURCES += $(wildcard util/compress/tests/*_config.c)
SEC_SOURCES += $(wildcard util/compress/tests/*.sec)

