COLLATE_SOURCES =



SOURCES += $(COLLATE_SOURCES:%.c=locale/collate/%.c)
SOURCES += $(wildcard locale/collate/*_config.c)
SEC_SOURCES += $(wildcard locale/collate/*.sec)

include locale/collate/tests/Makefile

