SIGWAIT_TESTS_SOURCES =



SOURCES += $(SIGWAIT_TESTS_SOURCES:%.c=signal/sigwait/tests/%.c)
SOURCES += $(wildcard signal/sigwait/tests/*_config.c)
SEC_SOURCES += $(wildcard signal/sigwait/tests/*.sec)

