TEXTDOMAIN_SOURCES =



SOURCES += $(TEXTDOMAIN_SOURCES:%.c=locale/textdomain/%.c)
SOURCES += $(wildcard locale/textdomain/*_config.c)
SEC_SOURCES += $(wildcard locale/textdomain/*.sec)

include locale/textdomain/tests/Makefile

