CONTEXT_SOURCES =



SOURCES += $(CONTEXT_SOURCES:%.c=process/context/%.c)
SOURCES += $(wildcard process/context/*_config.c)
SEC_SOURCES += $(wildcard process/context/*.sec)

include process/context/tests/Makefile

