CONTEXT_TESTS_SOURCES =



SOURCES += $(CONTEXT_TESTS_SOURCES:%.c=process/context/tests/%.c)
SOURCES += $(wildcard process/context/tests/*_config.c)
SEC_SOURCES += $(wildcard process/context/tests/*.sec)

