PGROUP_SOURCES =



SOURCES += $(PGROUP_SOURCES:%.c=process/pgroup/%.c)
SOURCES += $(wildcard process/pgroup/*_config.c)
SEC_SOURCES += $(wildcard process/pgroup/*.sec)

include process/pgroup/tests/Makefile

