BORDER_SOURCES =



SOURCES += $(BORDER_SOURCES:%.c=ncurses/border/%.c)
SOURCES += $(wildcard ncurses/border/*_config.c)
SEC_SOURCES += $(wildcard ncurses/border/*.sec)

include ncurses/border/tests/Makefile

