CHGAT_SOURCES =



SOURCES += $(CHGAT_SOURCES:%.c=ncurses/chgat/%.c)
SOURCES += $(wildcard ncurses/chgat/*_config.c)
SEC_SOURCES += $(wildcard ncurses/chgat/*.sec)

include ncurses/chgat/tests/Makefile

