RWLOCK_TESTS_SOURCES =



SOURCES += $(RWLOCK_TESTS_SOURCES:%.c=pthread/rwlock/tests/%.c)
SOURCES += $(wildcard pthread/rwlock/tests/*_config.c)
SEC_SOURCES += $(wildcard pthread/rwlock/tests/*.sec)

