#OLVer megabuilder

###############################################################################
# miss.c generator
###
generate_miss_c () {
    cat >miss.c <<EOF
/*
 * This file is generated by 'build_config.sh' script to handle missing functions under test.
 */
#include <stdio.h>

void sendExceptionFromCurrentThread(const char* buff);
void test_agent_recovery();

void __missing_function( const char* fname )
{
    char buff[1024];
    sprintf(buff, "Function not found in any library: %s", fname);
    sendExceptionFromCurrentThread(buff );
    test_agent_recovery();
}
EOF
}

###############################################################################
# Main
###

generate_miss_c

export OLVERTERM=$1
echo "Checking missing LSB symbols and libraries..."
# try making the package and collect the list of undefined library symbols
make >makelog 2>&1 
cat makelog | grep "undefined reference to" |sed -n 's/\([^`]\+\)`\([a-zA-Z_][a-zA-Z0-9_]\+\)\([^$]\)/\2/p' > undefined_symbols.txt
#cat makelog | grep "ld: cannot find -l" | awk -F'ld: cannot find -l' 'print $2' > undefined_libs.txt
rm -f makelog

echo missing
# create "miss.c" containing list of missing symbols
cat undefined_symbols.txt | sed -n 's/\([a-zA-Z0-9_]\)\+/void \0 ( void ) {__missing_function("\0");} /p' >>miss.c
gcc -I. -c miss.c -o miss.o
rm undefined_symbols.txt
