/*
 * This file is generated by 'build_config.sh' script to handle missing functions under test.
 */
#include <stdio.h>

void sendExceptionFromCurrentThread(const char* buff);
void test_agent_recovery();

void __missing_function( const char* fname )
{
    char buff[1024];
    sprintf(buff, "Function not found in any library: %s", fname);
    sendExceptionFromCurrentThread(buff );
    test_agent_recovery();
}
