PROCESS_META_SOURCES =


SOURCES += $(PROCESS_META_SOURCES:%.c=process/meta/%.c)
SOURCES += $(wildcard process/meta/*_config.c)
SEC_SOURCES += $(wildcard process/meta/*.sec)

include process/meta/tests/Makefile

