CONVERSION_TESTS_SOURCES =



SOURCES += $(CONVERSION_TESTS_SOURCES:%.c=util/conversion/tests/%.c)
SOURCES += $(wildcard util/conversion/tests/*_config.c)
SEC_SOURCES += $(wildcard util/conversion/tests/*.sec)

