WCTRANS_TESTS_SOURCES =



SOURCES += $(WCTRANS_TESTS_SOURCES:%.c=locale/wctrans/tests/%.c)
SOURCES += $(wildcard locale/wctrans/tests/*_config.c)
SEC_SOURCES += $(wildcard locale/wctrans/tests/*.sec)

