PTHREAD_SCHEDULER_TESTS_SOURCES =



SOURCES += $(PTHREAD_SCHEDULER_TESTS_SOURCES:%.c=pthread/scheduler/tests/%.c)
SOURCES += $(wildcard pthread/scheduler/tests/*_config.c)
SEC_SOURCES += $(wildcard pthread/scheduler/tests/*.sec)

