CONVERSION_SOURCES =



SOURCES += $(CONVERSION_SOURCES:%.c=util/conversion/%.c)
SOURCES += $(wildcard util/conversion/*_config.c)
SEC_SOURCES += $(wildcard util/conversion/*.sec)

include util/conversion/tests/Makefile

