CHSTR_SOURCES =



SOURCES += $(CHSTR_SOURCES:%.c=ncurses/chstr/%.c)
SOURCES += $(wildcard ncurses/chstr/*_config.c)
SEC_SOURCES += $(wildcard ncurses/chstr/*.sec)

include ncurses/chstr/tests/Makefile

