LOCALE_SOURCES =



SOURCES += $(LOCALE_SOURCES:%.c=locale/locale/%.c)
SOURCES += $(wildcard locale/locale/*_config.c)
SEC_SOURCES += $(wildcard locale/locale/*.sec)

include locale/locale/tests/Makefile

