COMPRESS_SOURCES =



SOURCES += $(COMPRESS_SOURCES:%.c=util/compress/%.c)
SOURCES += $(wildcard util/compress/*_config.c)
SEC_SOURCES += $(wildcard util/compress/*.sec)

include util/compress/tests/Makefile

