SOCKET_SOURCES =



SOURCES += $(SOCKET_SOURCES:%.c=socket/socket/%.c)
SOURCES += $(wildcard socket/socket/*_config.c)
SEC_SOURCES += $(wildcard socket/socket/*.sec)

include socket/socket/tests/Makefile

