TERMINAL_TESTS_SOURCES =



SOURCES += $(TERMINAL_TESTS_SOURCES:%.c=ncurses/terminal/tests/%.c)
SOURCES += $(wildcard ncurses/terminal/tests/*_config.c)
SEC_SOURCES += $(wildcard ncurses/terminal/tests/*.sec)

