CLEAR_SOURCES =



SOURCES += $(CLEAR_SOURCES:%.c=ncurses/clear/%.c)
SOURCES += $(wildcard ncurses/clear/*_config.c)
SEC_SOURCES += $(wildcard ncurses/clear/*.sec)

include ncurses/clear/tests/Makefile

