RESOURCES_TESTS_SOURCES =



SOURCES += $(RESOURCES_TESTS_SOURCES:%.c=process/resources/tests/%.c)
SOURCES += $(wildcard process/resources/tests/*_config.c)
SEC_SOURCES += $(wildcard process/resources/tests/*.sec)

