SCHEDULER_TESTS_SOURCES =



SOURCES += $(SCHEDULER_TESTS_SOURCES:%.c=process/scheduler/tests/%.c)
SOURCES += $(wildcard process/scheduler/tests/*_config.c)
SEC_SOURCES += $(wildcard process/scheduler/tests/*.sec)

