BORDER_TESTS_SOURCES =



SOURCES += $(BORDER_TESTS_SOURCES:%.c=ncurses/border/tests/%.c)
SOURCES += $(wildcard ncurses/border/tests/*_config.c)
SEC_SOURCES += $(wildcard ncurses/border/tests/*.sec)

