$quote "

$set 12345

123 The first message string

321 As children, everyone is taught the traditional \
order of the nine planets in the solar system. However, \
as we learn more about our neighboring planets and space \
in general this may have to be changed. Between and \
beyond Neptune and Pluto, thousands of small, somewhat \
planet-like objects have been found. These have been \
shown to occupy three distinct areas: the Kuiper belt, \
the scattered disc, and the Oort cloud. The discoveries \
have so far had two major implications:

$set 54321

907 The last message string