$quote "

$set 94758

333 In the early- to mid-1950s, Dr. Paul \
Kuroda from the University of Arkansas described \
the possibility of naturally occurring nuclear \
reactors lurking in the crust of ancient Earth. \
The key is an isotope of Uranium called U-235, \
which occurs naturally in small amounts. If enough \
of this isotope were pooled together under \
specific circumstances, Kuroda theorized, the \
natural reactor would go critical, and self-sustaining \
fission would occur.

$set 10283

628 The other message string