$quote "

$set 32145

951 Error message

952 klasdfkladsklfkl 2435 2vmkd 1 453sjdk5 345 fiw345 \
345e45 4o4j kd klalkfjdiweo kw239 9034 iw j

953 Color film was non-existent in 1909 Russia, yet in that year \
a photographer named Sergei Mikhailovich Prokudin-Gorskii embarked \
on a photographic survey of his homeland and captured hundreds of \
photos in full, vivid color. His photographic plates were black and \
white, but he had developed an ingenious photographic technique which \
allowed him to use them to produce accurate color images.

$set 94758

333 The one message string