NCURSES_STRING_TESTS_SOURCES =



SOURCES += $(NCURSES_STRING_TESTS_SOURCES:%.c=ncurses/string/tests/%.c)
SOURCES += $(wildcard ncurses/string/tests/*_config.c)
SEC_SOURCES += $(wildcard ncurses/string/tests/*.sec)

