NETDATA_TESTS_SOURCES =



SOURCES += $(NETDATA_TESTS_SOURCES:%.c=socket/netdata/tests/%.c)
SOURCES += $(wildcard socket/netdata/tests/*_config.c)
SEC_SOURCES += $(wildcard socket/netdata/tests/*.sec)

