INTEGER_SOURCES =



SOURCES += $(INTEGER_SOURCES:%.c=math/integer/%.c)
SOURCES += $(wildcard math/integer/*_config.c)
SEC_SOURCES += $(wildcard math/integer/*.sec)

include math/integer/tests/Makefile

