SCHEDULER_SOURCES =



SOURCES += $(SCHEDULER_SOURCES:%.c=process/scheduler/%.c)
SOURCES += $(wildcard process/scheduler/*_config.c)
SEC_SOURCES += $(wildcard process/scheduler/*.sec)

include process/scheduler/tests/Makefile

