COLOR_SOURCES =



SOURCES += $(COLOR_SOURCES:%.c=ncurses/color/%.c)
SOURCES += $(wildcard ncurses/color/*_config.c)
SEC_SOURCES += $(wildcard ncurses/color/*.sec)

include ncurses/color/tests/Makefile

