MESSAGES_TESTS_SOURCES =



SOURCES += $(MESSAGES_TESTS_SOURCES:%.c=locale/messages/tests/%.c)
SOURCES += $(wildcard locale/messages/tests/*_config.c)
SEC_SOURCES += $(wildcard locale/messages/tests/*.sec)

