PROCESS_TESTS_SOURCES =



SOURCES += $(PROCESS_TESTS_SOURCES:%.c=process/process/tests/%.c)
SOURCES += $(wildcard process/process/tests/*_config.c)
SEC_SOURCES += $(wildcard process/process/tests/*.sec)

