MULTIPLEX_TESTS_SOURCES =



SOURCES += $(MULTIPLEX_TESTS_SOURCES:%.c=io/multiplex/tests/%.c)
SOURCES += $(wildcard io/multiplex/tests/*_config.c)
SEC_SOURCES += $(wildcard io/multiplex/tests/*.sec)

