SYSCONF_TESTS_SOURCES =



SOURCES += $(SYSCONF_TESTS_SOURCES:%.c=system/sysconf/tests/%.c)
SOURCES += $(wildcard system/sysconf/tests/*_config.c)
SEC_SOURCES += $(wildcard system/sysconf/tests/*.sec)

