WCOLLATE_TESTS_SOURCES =



SOURCES += $(WCOLLATE_TESTS_SOURCES:%.c=locale/wcollate/tests/%.c)
SOURCES += $(wildcard locale/wcollate/tests/*_config.c)
SEC_SOURCES += $(wildcard locale/wcollate/tests/*.sec)

