NCURSES_STRING_SOURCES =



SOURCES += $(NCURSES_STRING_SOURCES:%.c=ncurses/string/%.c)
SOURCES += $(wildcard ncurses/string/*_config.c)
SEC_SOURCES += $(wildcard ncurses/string/*.sec)

include ncurses/string/tests/Makefile

