INPUT_SOURCES =



SOURCES += $(INPUT_SOURCES:%.c=ncurses/input/%.c)
SOURCES += $(wildcard ncurses/input/*_config.c)
SEC_SOURCES += $(wildcard ncurses/input/*.sec)

include ncurses/input/tests/Makefile

