WINDOW_TESTS_SOURCES =



SOURCES += $(WINDOW_TESTS_SOURCES:%.c=ncurses/window/tests/%.c)
SOURCES += $(wildcard ncurses/window/tests/*_config.c)
SEC_SOURCES += $(wildcard ncurses/window/tests/*.sec)

