WCOLLATE_SOURCES =



SOURCES += $(WCOLLATE_SOURCES:%.c=locale/wcollate/%.c)
SOURCES += $(wildcard locale/wcollate/*_config.c)
SEC_SOURCES += $(wildcard locale/wcollate/*.sec)

include locale/wcollate/tests/Makefile

