COLLATE_TESTS_SOURCES =



SOURCES += $(COLLATE_TESTS_SOURCES:%.c=locale/collate/tests/%.c)
SOURCES += $(wildcard locale/collate/tests/*_config.c)
SEC_SOURCES += $(wildcard locale/collate/tests/*.sec)

