PROCESS_META_TESTS_SOURCES =



SOURCES += $(PROCESS_META_TESTS_SOURCES:%.c=process/meta/tests/%.c)
SOURCES += $(wildcard process/meta/tests/*_config.c)
SEC_SOURCES += $(wildcard process/meta/tests/*.sec)

