SCREEN_TESTS_SOURCES =



SOURCES += $(SCREEN_TESTS_SOURCES:%.c=ncurses/screen/tests/%.c)
SOURCES += $(wildcard ncurses/screen/tests/*_config.c)
SEC_SOURCES += $(wildcard ncurses/screen/tests/*.sec)

