COMPLEX_SOURCES =



SOURCES += $(COMPLEX_SOURCES:%.c=math/complex/%.c)
SOURCES += $(wildcard math/complex/*_config.c)
SEC_SOURCES += $(wildcard math/complex/*.sec)

include math/complex/tests/Makefile

